---
- name: Setup LXC container
  hosts: "pi_hole_1"
  vars_files:
    - config/container.yaml
  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Ensure locale exists
      community.general.locale_gen:
        name: "{{ lxc.locale }}"
        state: present

    - name: Ensure language locale exists
      community.general.locale_gen:
        name: "{{ lxc.lang }}"
        state: present

    - name: Get current locale configuration
      ansible.builtin.command: "localectl status"
      register: locale_status
      changed_when: false
      failed_when: false

    - name: Parse 'LANG' from current locale and language configuration
      set_fact:
        locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | default(['none'], true) | first }}"

    - name: Parse 'LANGUAGE' from current locale and language configuration
      set_fact:
        locale_language: "{{ locale_status.stdout | regex_search('LANGUAGE=([^\n]+)', '\\1') | default([locale_lang], true) | first }}"

    - name: Configure locale to '{{ lxc.locale }}' and language to '{{ lxc.lang }}'
      become: yes
      command: localectl set-locale LANG={{ lxc.lang }} LANGUAGE={{ lxc.locale }}
      changed_when: locale_lang != lxc.lang or locale_language != lxc.locale
