---
- name: Check distribution
  ansible.builtin.debug:
    msg: "Distribution is {{ ansible_distribution }}"
  failed_when: "ansible_distribution not in ['Ubuntu','Debian']"

- name: Install qemu-guest-agent
  become: true
  ansible.builtin.package:
    update_cache: yes
    name: qemu-guest-agent
    state: present

- name: Enable qemu-guest-agent service
  become: true
  ansible.builtin.systemd:
    name: qemu-guest-agent
    enabled: true
    state: started