---
- name: Create Jellyfin VM
  hosts: localhost
  gather_facts: false
  vars_files:
    - config/vm_vars.yaml
    - ../ansible.global_vars.yaml
  vars:
    target_ansible_pve_host: "pve_nas"
  tasks:
    - name: Download the image
      ansible.builtin.uri:
        url: "{{ jellyfin.image.url }}"
        dest: "/var/lib/vz/template/iso/{{ jellyfin.image.filename }}"
        status_code: [200, 304]
      delegate_to: "{{ target_ansible_pve_host }}"

    - name: Copy ci custom files
      block:
        - name: Ensure snippets folder exists
          ansible.builtin.file:
            path: "{{ jellyfin.image.cloudinit.folder }}"
            state: directory
            mode: "0755"
        - name: Copy user-data
          ansible.builtin.template:
            src: config/user.yaml.j2
            dest: "{{ jellyfin.image.cloudinit.folder }}/user_{{ jellyfin.vmid }}"
            mode: "0644"
        - name: Copy network-data
          ansible.builtin.template:
            src: config/network.yaml.j2
            dest: "{{ jellyfin.image.cloudinit.folder }}/net_{{ jellyfin.vmid }}"
            mode: "0644"
      delegate_to: "{{ target_ansible_pve_host }}"

    - name: Create Jellyfin VM
      community.general.proxmox_kvm:
        api_host: "{{ pve_api.host }}"
        api_user: "{{ pve_api.user }}@{{ pve_api.realm }}"
        api_password: "{{ pve_api.password }}"
        node: "{{ jellyfin.node }}"
        vmid: "{{ jellyfin.vmid }}"
        state: present
        name: "{{ jellyfin.name }}"
        ostype: "{{ jellyfin.ostype }}"
        onboot: "{{ jellyfin.onboot }}"
        agent: "{{ jellyfin.agent }}"
        bios: "{{ jellyfin.bios }}"
        cpu: "{{ jellyfin.cpu }}"
        sockets: "{{ jellyfin.sockets }}"
        cores: "{{ jellyfin.cores }}"
        memory: "{{ jellyfin.memory }}"
        balloon: "{{ jellyfin.balloon }}"
        scsihw: "{{ jellyfin.scsihw }}"
        ide:
          ide2: "{{ jellyfin.storage }}:cloudinit"
        net:
          net0: "model=virtio,bridge={{ jellyfin.net.host_bridge }},firewall=1,macaddr={{ jellyfin.net.macaddr }}"
        tags: "{{ jellyfin.tags }}"
        cicustom: "user=local:snippets/user_{{ jellyfin.vmid }},network=local:snippets/net_{{ jellyfin.vmid }}"

    - name: Import cloud image
      community.general.proxmox_disk:
        api_host: "{{ pve_api.host }}"
        api_user: "{{ pve_api.user }}@{{ pve_api.realm }}"
        api_password: "{{ pve_api.password }}"
        vmid: "{{ jellyfin.vmid }}"
        import_from: "/var/lib/vz/template/iso/{{ jellyfin.image.filename }}"
        storage: "{{ jellyfin.storage }}"
        disk: "{{ jellyfin.disk_name }}"
        state: present

    - name: Check VM config for optional updates
      community.general.proxmox_vm_info:
        api_host: "{{ pve_api.host }}"
        api_user: "{{ pve_api.user }}@{{ pve_api.realm }}"
        api_password: "{{ pve_api.password }}"
        node: "{{ jellyfin.node }}"
        vmid: "{{ jellyfin.vmid }}"
        config: current
      register: "vm_info"

    - name: Register disk sizes and boot order for optional updates
      ansible.builtin.set_fact:
        disk_sizes: "{{ vm_info.proxmox_vms[0].config.scsi0 | regex_search('size=(.*)', '\\1') }}"
        boot: "{{ vm_info.proxmox_vms[0].config.boot }}"

    - name: Resize the boot disk
      community.general.proxmox_disk:
        api_host: "{{ pve_api.host }}"
        api_user: "{{ pve_api.user }}@{{ pve_api.realm }}"
        api_password: "{{ pve_api.password }}"
        vmid: "{{ jellyfin.vmid }}"
        disk: "{{ jellyfin.disk_name }}"
        state: resized
        size: "{{ jellyfin.disk_size }}"
      when: "disk_sizes[0] != jellyfin.disk_size"

    - name: Set boot order to disk
      community.general.proxmox_kvm:
        api_host: "{{ pve_api.host }}"
        api_user: "{{ pve_api.user }}@{{ pve_api.realm }}"
        api_password: "{{ pve_api.password }}"
        node: "{{ jellyfin.node }}"
        vmid: "{{ jellyfin.vmid }}"
        update: true
        boot: "{{ jellyfin.boot }}"
        bootdisk: "{{ jellyfin.disk_name }}"
      when: "boot != jellyfin.boot"

    - name: Start the VM
      community.general.proxmox_kvm:
        api_host: "{{ pve_api.host }}"
        api_user: "{{ pve_api.user }}@{{ pve_api.realm }}"
        api_password: "{{ pve_api.password }}"
        node: "{{ jellyfin.node }}"
        vmid: "{{ jellyfin.vmid }}"
        state: started

    - name: Create initial Snapshot with bare machine
      community.general.proxmox_snap:
        api_host: "{{ pve_api.host }}"
        api_user: "{{ pve_api.user }}@{{ pve_api.realm }}"
        api_password: "{{ pve_api.password }}"
        vmid: "{{ jellyfin.vmid }}"
        snapname: "{{ jellyfin.snapshot.name }}"
        description: "{{ jellyfin.snapshot.description }}"
        state: present
        vmstate: false
